modLoader = "kotlinforforge"

loaderVersion = "[3,)"
license = "GNU-GPL-3.0"
issueTrackerURL = "https://github.com/ExampleUser/ExampleMod/issues"

[[mods]]
modId = "examplemod"
version = "1.0.0"
displayName = "ExampleMod"
authors = "ExampleUser"
description = '''
Examplemod description
'''
updateJSONURL="https://raw.githubusercontent.com/ExampleUser/ExampleMod/main/updates.json"
#logoFile="icon.png"
[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "CLIENT"
